### ISSUE TITLE
intent returned for all words spoken  Bug: 🐛 

### ISSUE THREAD

**Issue by thiyaga05** [speechly/speechly#105]
**### Using @speechly/browser-client**

-  Gave one sample intent like **short_notes** with list **take_notes** and tried saying other sample words **(something else)** which doesn't match to the given intent, but got response for same intent. 
- Also got more than one response for single voice input in speechly dashboard app console as well as in my local machine. 
- Note:  These are done with **starter pricing** in speechly 

**For Reference: check the below images**

![Screenshot (1)](https://user-images.githubusercontent.com/95863958/146495464-c55b28df-7fe3-4f2f-abe0-ea34c84e2005.png)
![Screenshot (2)](https://user-images.githubusercontent.com/95863958/146495470-b27eb572-8db3-4514-8318-add45cdaf04f.png)

Can you try to sort out this??

**Comment by aukkonen** [comment]
@thiyaga05
About getting an intent for an "unrelated" utterance:
Yes, this is the way our system is currently designed to work. That is, it does not distinguish between related and unrelated utterances, but considers everything the user says as potentially relevant, and thus maps every utterance to one of the intents.

If you need to catch unrelated utterances, you must design a separate "catchall" intent that matches these. Our recommended way to do this is to collect a number (~100 or so) of such utterances, try to make them as diverse as possible but not overlapping with our actual intents, and include these as part of your configuration.

About receiving multiple responses:
This is also how our API is designed to work. Rather than returning a single response, our API sends back a stream of responses that represent an accumulated view of the speech recognition results. This is to allow the UI to respond as quickly as possible after the user has started speaking. While we recommend updating the UI as new responses are received, you can also wait until the ongoing "segment" object has its final flag set to true, and only read the fields of the segment at this point.
